**Q1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [ ]:
import numpy as np

array = np.random.randint(1, 101, (3, 3))

transposed_array = np.transpose(array)

print("Original Array:")
print(array)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[38 97 13]
 [78 91 32]
 [78 98 71]]

Transposed Array:
[[38 78 78]
 [97 91 98]
 [13 32 71]]


**Q2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array**

In [ ]:
import numpy as np

one_d_array = np.arange(10)

a1 = one_d_array.reshape(2, 5)

a2 = one_d_array.reshape(5, 2)

print("1D Array:")
print(one_d_array)

print("\nReshaped into 2x5 Array:")
print(a1)

print("\nReshaped into 5x2 Array:")
print(a2)


1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**Q3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [ ]:
array_4x4 = np.random.rand(4, 4)

array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_4x4, array_with_border



(array([[0.10683336, 0.37282282, 0.42438233, 0.36719258],
        [0.65431322, 0.95330446, 0.44946632, 0.44177542],
        [0.60803117, 0.31872317, 0.24844665, 0.33170441],
        [0.35192218, 0.86371453, 0.81665455, 0.53125333]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.10683336, 0.37282282, 0.42438233, 0.36719258,
         0.        ],
        [0.        , 0.65431322, 0.95330446, 0.44946632, 0.44177542,
         0.        ],
        [0.        , 0.60803117, 0.31872317, 0.24844665, 0.33170441,
         0.        ],
        [0.        , 0.35192218, 0.86371453, 0.81665455, 0.53125333,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

**Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [ ]:
import numpy as np

array_integer = np.arange(10,60,5)

array_integer


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

**Q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element**

In [2]:
import numpy as np


string_array = np.array(['python', 'numpy', 'pandas'])

upper_case = np.char.upper(string_array)
lower_case = np.char.lower(string_array)
title_case = np.char.title(string_array)
capitalize_case = np.char.capitalize(string_array)

print("Original Array:", string_array)
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title Case:", title_case)
print("Capitalize Case:", capitalize_case)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize Case: ['Python' 'Numpy' 'Pandas']


**Q6.Generate a NumPy array of words. Insert a space between each character of every word in the array**

In [4]:
import numpy as np

words_array = np.array(['Swetank', 'Kumar', 'Singh'])

spaced_words = np.char.join(' ', words_array)

print("Original Array:", words_array)
print("Array with spaces between characters:", spaced_words)


Original Array: ['Swetank' 'Kumar' 'Singh']
Array with spaces between characters: ['S w e t a n k' 'K u m a r' 'S i n g h']


**Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [6]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

addition_result = array1 + array2
print("Addition result:\n", addition_result)

subtraction_result = array1 - array2
print("Subtraction result:\n", subtraction_result)

multiplication_result = array1 * array2
print("Multiplication result:\n", multiplication_result)

division_result = array1 / array2
print("Division result:\n", division_result)


Addition result:
 [[ 8 10 12]
 [14 16 18]]
Subtraction result:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication result:
 [[ 7 16 27]
 [40 55 72]]
Division result:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


**Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [7]:
import numpy as np

identity_matrix = np.eye(5)

diagonal_elements = identity_matrix.diagonal()

print("Identity matrix:\n", identity_matrix)
print("Diagonal elements:", diagonal_elements)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements: [1. 1. 1. 1. 1.]


**Q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array**

In [9]:
import numpy as np

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

random_integers = np.random.randint(0, 1001, size=100)

prime_numbers = [num for num in random_integers if is_prime(num)]

print("Original Array of Random Integers:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Original Array of Random Integers:
[ 847  681   28  386  281   72  162  808  660  936  921  853  424  962
  125  550  848  187   20  399  239  245  373  681  795   27  223  535
  877  419  939  272  179  884  404  198  988   54  916  440  726  967
  700  696  355  774   85  945  807 1000  178  586  463  743  883   97
  686  134  573  375  142   47  779  499  856  402  258  560  288  157
  232  239  526   23  941  661   34  135  372  549  736  381  798  777
  247  355  909  777  141  217  761  528  625  386  795  700   14  299
   29  164]

Prime Numbers in the Array:
[281, 853, 239, 373, 223, 877, 419, 179, 967, 463, 743, 883, 97, 47, 499, 157, 239, 23, 941, 661, 761, 29]


**Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

In [16]:
import numpy as np

daily_temperatures = np.random.randint(15, 35, size=30)

weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, 30,7)]

print("Daily Temperatures:")
print(daily_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)



Daily Temperatures:
[19 16 20 21 33 17 24 19 33 15 26 31 24 22 32 24 28 23 33 28 33 26 29 21
 17 24 24 15 17 22]

Weekly Averages:
[21.428571428571427, 24.285714285714285, 28.714285714285715, 22.285714285714285, 19.5]
